#!/bin/bash
#
# Tomcat init script
# chkconfig: 2345 96 14
#
JDK_HOME=/usr/local/jdk
CATALINA_HOME=/usr/local/tomcat
export JDK_HOME CATALINA_HOME
source /etc/profile

start() {
   	if lsof -i:8080 &> /dev/null;then
   	    echo "Tomcat already running!!"  
  	else 
	    echo "Tomcat is dead. Now start Tomcat..."
  	    $CATALINA_HOME/bin/catalina.sh start  &> /dev/null
	    sleep 5
   	    if lsof -i:8080 &> /dev/null;then
		PID=`ps -ef | grep  tomcat | grep jdk | awk '{print $2}'`
		PS_NUM=`ps -ef | grep  tomcat | grep jdk | awk '{print $2}' | wc -l`
  		echo  "Done. Tomcat now is running. PID=$PID"
	    else
		echo "Tomcat not start , start it again."
  	        $CATALINA_HOME/bin/catalina.sh start  &> /dev/null
	    fi
 	fi
	}

stop() {
	PID=`ps -ef  | grep  -v grep  | grep java | awk  '{print $2}'`
	PS_NUM=`ps -ef | grep  -v "color"  | grep tomcat | awk '{print $2}' | wc -l`
   	if lsof -i:8080 &> /dev/null;then
	    echo "Tomcat is running, now stop..."
            $CATALINA_HOME/bin/catalina.sh stop  &> /dev/null
	    pkill java && pkill tomcat
	    sleep 5
       	    if  netstat -an | grep 8080 | grep LISTEN >/dev/null;then
		PID=`ps -ef  | grep  -v grep  | grep java | awk  '{print $2}'`
		PS_NUM=`ps -ef | grep  -v "color"  | grep tomcat | awk '{print $2}' | wc -l`
		kill -9 $PID  &> /dev/null
	    else
  		echo  "Tomcat stop done." 
	    fi
	else
		echo "Tomcat is not running."
	fi
	if  netstat -an | grep 8080 | grep LISTEN >/dev/null;then
            PID=`ps -ef  | grep  -v grep  | grep java | awk  '{print $2}'`
            echo "Tomcat still running, kill it..."
            pkill tomcat ;sleep 1 
            if  netstat -an | grep 8080 | grep LISTEN >/dev/null;then
                echo "Still running."
                pkill java; sleep 1
            fi
	fi
	}

restart() {
	stop 
	start 
 }

status(){


    if lsof -i:8080 &> /dev/null; then
        echo 1
    else 
	echo 0
    fi

}

case "$1" in 
start) 
start 
;; 

stop) 
stop 
;; 

restart) 
restart 
;; 

status)
    status
;;
*) 
echo $"Usage: $0 {start|stop|restart|status}" 
esac
